from pathlib import Path
import re

P=Path("index.html")
s=P.read_text(encoding="utf-8")

# Turn the existing card collection into a social-feed presentation without
# duplicating the canonical content already generated by app.py.
s=s.replace('<main class="main" id="explore">','<main class="main" id="explore"><div class="feed-shell">',1)
s=s.replace('</main>\n<footer','</div></main>\n<footer',1)

css=r'''
<style id="npcbook-feed-upgrade">
:root{--feed-max:1180px;--feed-col:620px;--x-bg:#000;--x-panel:#000;--x-border:#202833;--x-text:#e7e9ea;--x-muted:#71767b;--x-blue:#1d9bf0}
body{background:var(--x-bg)!important;color:var(--x-text)!important}
.topbar{background:#000e!important;border-bottom:1px solid var(--x-border)!important}
.nav{max-width:var(--feed-max)!important}
.hero,.stats{display:none!important}
.main{max-width:var(--feed-max)!important;margin:auto!important;padding:0!important;display:grid!important;grid-template-columns:220px minmax(0,var(--feed-col)) 300px!important;gap:22px!important}
.main:before{content:"NPCBOOK · BLSSNVJ21\A\A⌂  Home\A👤  NPCs\A🌍  Worlds\A⚔  Quests\A📜  Lore\A🔥  Trending\A⚙  Settings";white-space:pre;position:sticky;top:70px;height:fit-content;padding:20px 12px;color:#e7e9ea;font-weight:800;line-height:2.45;border-right:1px solid var(--x-border)}
.feed-shell{min-width:0;border-left:1px solid var(--x-border);border-right:1px solid var(--x-border)}
.main:after{content:"TRENDING\A\A#PigeonCouncil\AThe pigeons know too much.\A\A#BLSSNVJ21\AThe signal is still blinking.\A\A#IronLegion\AThe lava road remains lava.";white-space:pre-wrap;position:sticky;top:70px;height:fit-content;margin-top:20px;padding:18px;background:#0a0a0a;border:1px solid var(--x-border);border-radius:18px;color:#9ca3af;line-height:1.55}
.toolbar{position:sticky!important;top:58px!important;z-index:20;background:#000e!important;backdrop-filter:blur(14px);margin:0!important;padding:13px 16px!important;border-bottom:1px solid var(--x-border)}
.filters{display:none!important}.result-count{margin-left:auto;color:var(--x-muted)!important}
.feed-banner{display:flex;justify-content:space-between;gap:10px;padding:15px 18px;border-bottom:1px solid var(--x-border);font-weight:900;font-size:20px}.feed-banner small{font-size:12px;color:var(--x-muted);font-weight:500}
.composer{background:#000!important;border-bottom:1px solid var(--x-border)!important;padding:16px 18px!important}
.grid{display:block!important}.card{background:#000!important;border:0!important;border-bottom:1px solid var(--x-border)!important;border-radius:0!important;padding:16px 18px!important;min-height:0!important}
.card:hover{background:#050505!important;transform:none!important;box-shadow:none!important}
.card h3{font-size:18px!important;margin:8px 0 6px!important}.card p{font-size:15px!important;color:#d9d9d9!important;line-height:1.5}
.card-top:before{content:"🤖";width:42px;height:42px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(135deg,#7c6cff,#31d8ff);float:left;margin-right:11px}
.card .icon-btn{background:transparent!important;border:0!important;color:var(--x-muted)!important}.card-actions{margin-top:11px!important}.card-actions .btn{border:0!important;background:transparent!important;color:var(--x-muted)!important}
.card-actions .btn:hover{color:var(--x-blue)!important}
.empty{border:0!important}
@media(max-width:980px){.main{grid-template-columns:72px minmax(0,var(--feed-col))!important;max-width:700px!important}.main:before{content:"⌂\A👤\A🌍\A⚔\A📜\A🔥\A⚙";font-size:22px;text-align:center;line-height:3.05;padding:18px 5px}.main:after{display:none!important}}
@media(max-width:650px){.main{display:block!important;width:100%!important}.main:before,.main:after{display:none!important}.feed-shell{border:0!important}.toolbar{top:96px!important}.card{padding:15px 14px!important}.composer{padding:13px 14px!important}}
</style>
'''
s=s.replace('</head>',css+'</head>',1)

js=r'''
<script id="npcbook-feed-engine">
(()=>{window.addEventListener("error",e=>{if(e.error)console.error("NPCBook runtime error:",e.error);});window.addEventListener("unhandledrejection",e=>{console.error("NPCBook promise error:",e.reason);e.preventDefault();});const K="npcbook-feed-v14",grid=document.getElementById("resultsGrid"),search=document.getElementById("search"),cards=[...document.querySelectorAll(".card")];if(!grid||!cards.length)return;
const read=k=>{try{return JSON.parse(localStorage.getItem(K+"-"+k)||"null")}catch(_){return null}},write=(k,v)=>localStorage.setItem(K+"-"+k,JSON.stringify(v));
let seen=new Set(read("seen")||[]),filter=read("filter")||"all",query=read("query")||"";
const id=c=>{try{return JSON.parse(c.dataset.item).id}catch(_){return c.dataset.item}};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function toast(m){let t=document.getElementById("feedToast");if(!t){t=document.createElement("div");t.id="feedToast";t.style.cssText="position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:999;background:#e7e9ea;color:#050505;padding:10px 16px;border-radius:999px;font-weight:800;box-shadow:0 10px 30px #0008";document.body.appendChild(t)}t.textContent=m;t.style.opacity="1";clearTimeout(t._x);t._x=setTimeout(()=>t.style.opacity="0",1800)}
function banner(){if(document.querySelector(".feed-banner"))return;let b=document.createElement("div");b.className="feed-banner";b.innerHTML="<span>For you ⚡</span><small>BLSSNVJ21 · chaotic mode · no repeats</small>";grid.parentNode.insertBefore(b,grid)}
function composer(){if(document.getElementById("localComposer"))return;let b=document.createElement("section");b.id="localComposer";b.className="composer";b.innerHTML='<div class="avatar">🤖</div><div class="composebox"><textarea maxlength="280" placeholder="What is happening in the omniverse?"></textarea><div class="compose-actions"><small><span>0</span>/280 · saved locally</small><button class="btn primary">Post nonsense</button></div></div>';grid.parentNode.insertBefore(b,grid);let ta=b.querySelector("textarea"),n=b.querySelector("small span"),draft=localStorage.getItem(K+"-draft")||"";ta.value=draft;n.textContent=draft.length;ta.oninput=()=>{n.textContent=ta.value.length;localStorage.setItem(K+"-draft",ta.value)};b.querySelector("button").onclick=()=>{let v=ta.value.trim();if(!v)return toast("The void requires words.");let p=read("posts")||[];p.unshift({id:"local-"+Date.now(),text:v,time:new Date().toISOString()});write("posts",p.slice(0,50));ta.value="";localStorage.removeItem(K+"-draft");toast("Broadcast stored locally. The pigeons approve.")}}
function localPosts(){return read("posts")||[]}function localCard(p){let c=document.createElement("article");c.className="card local-post";c.dataset.local="1";c.innerHTML='<div class="card-top"><span class="eyebrow">🤖 LOCAL · BLSSNVJ21</span><button class="icon-btn" type="button" aria-label="Delete post">×</button></div><h3>Anonymous NPC</h3><p></p><div class="meta"><span>just now</span><span>stored on this device</span></div><div class="card-actions"><button class="btn small ghost" type="button">❤️ Like</button></div>';c.querySelector("p").textContent=p.text;c.querySelector(".icon-btn").onclick=()=>{write("posts",localPosts().filter(x=>x.id!==p.id));c.remove();toast("Post deleted locally.")};c.querySelector(".btn").onclick=()=>{let likes=read("likes")||{};likes[p.id]=(likes[p.id]||0)+1;write("likes",likes);toast("❤️ "+likes[p.id]+" local approval")};return c}
function render(){let fresh=cards.filter(c=>!seen.has(id(c))&&(filter==="all"||c.dataset.type===filter)&&(!query||c.dataset.search.toLowerCase().includes(query)));if(!fresh.length){seen=new Set();fresh=cards.filter(c=>(filter==="all"||c.dataset.type===filter)&&(!query||c.dataset.search.toLowerCase().includes(query)));if(fresh.length)toast("Feed exhausted. New chaos cycle unlocked.")}fresh=shuffle(fresh.slice());grid.innerHTML="";localPosts().filter(p=>!query||p.text.toLowerCase().includes(query)).slice(0,20).forEach(p=>grid.appendChild(localCard(p)));fresh.forEach(c=>{grid.appendChild(c);seen.add(id(c))});write("seen",[...seen]);write("filter",filter);write("query",query);let rc=document.getElementById("resultCount");if(rc)rc.textContent=(fresh.length+localPosts().length)+" posts";let empty=document.getElementById("empty");if(empty)empty.classList.toggle("show",!fresh.length&&!localPosts().length)}
window.setFilter=f=>{filter=f;render()};search.addEventListener("input",e=>{query=e.target.value.trim().toLowerCase();seen=new Set();render()});
document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement!==search){e.preventDefault();search.focus()}});
cards.forEach(c=>c.addEventListener("dblclick",()=>{let i=JSON.parse(c.dataset.item),likes=read("likes")||{};likes[i.id]=(likes[i.id]||0)+1;write("likes",likes);toast("❤️ "+likes[i.id]+" local approval for "+i.name)}));
banner();composer();search.value=query;render();
window.NPCBookFeed={reset:()=>{seen=new Set();localStorage.removeItem(K+"-seen");render();toast("Timeline reset. History vaporized.")},clear:()=>{Object.keys(localStorage).filter(k=>k.startsWith(K)).forEach(k=>localStorage.removeItem(k));location.reload()}};
})();
</script>
'''
s=s.replace('</body>',js+'</body>',1)
P.write_text(s,encoding="utf-8")
print("feed upgrade applied")
